<a href="https://colab.research.google.com/github/Faith-Mueni/Python-Data-Analysis/blob/main/DailyPractice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
"Import the numpy package under the name np"
import numpy as np



In [ ]:
"How to get the documentation of the numpy add function from the command line"
get_ipython().run_line_magic('run','')

In [ ]:
"Print the numpy version and the configuration"
print (np.__version__)
np.show_config()


1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [4]:
"Create a null vector of size 10"
x = np.zeros(10)
print (x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
"How to find the memory size of any array"
x = np.zeros ((10,10,10))
print("%d bytes" % (x.size * x.itemsize))

8000 bytes


In [15]:
"Create a null vector of size 10 but the fifth value which is 1"
x = np.zeros(10)
x[4]=1
print (x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
"Create a vector with values ranging from 10 to 49"
x = np.arange(10,50)
print (x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
"Reverse a vector (first element becomes last)"
x = np.arange (10,50)
x = x [::-1]
x [4]= 20
print (x)


[49 48 47 46 20 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
"Create a 3x3 matrix with values ranging from 0 to 8"
x = np.arange (9).reshape(3,3)
print (x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
"Find indices of non-zero elements from [1,2,0,0,4,0]"
x = np.nonzero ([1,2,0,0,4,0])
print (x)

(array([0, 1, 4]),)


In [22]:
"Create a 3x3 identity matrix"
x = np.eye(3)
print (x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
"Create a 3x3x3 array with random values"
x = np.random.random([3,3,3])
print(x)

[[[0.29940931 0.118167   0.93432762]
  [0.70505214 0.36206423 0.88305202]
  [0.3947187  0.13125509 0.24769145]]

 [[0.79092885 0.02808737 0.83328817]
  [0.2331976  0.37096615 0.71061712]
  [0.84835544 0.53393102 0.30402806]]

 [[0.09820342 0.19341058 0.46693142]
  [0.70569826 0.42109392 0.65028338]
  [0.62684892 0.66960344 0.33171647]]]


In [28]:
"Create a 10x10 array with random values and find the minimum and maximum values"
Z = np.random.random ([10,10])
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


0.04794820648738918 0.9999207198657326


In [30]:
"Create a random vector of size 30 and find the mean value"
x =np.random.random(30)
X = x.mean()
print(X)

0.499579214553593


In [31]:
"Create a 2d array with 1 on the border and 0 inside"
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
