<a href="https://colab.research.google.com/github/Faith-Mueni/Python-Data-Analysis/blob/main/NumpyWeeklyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [115]:
"Find the nearest value from a given value in an array"
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5435985275840334


In [114]:
"Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?"
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [113]:
"Create an array class that has a name attribute"
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [112]:
"Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)"
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 4. 3. 2. 5. 2. 3. 1. 1.]


In [110]:
"How to accumulate elements of a vector (X) to an array (F) based on an index list (I)"
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [109]:
" Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors"
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [108]:
"Considering a four dimensions array, how to get sum over the last two axis at once"
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[37 62 43 63]
 [57 40 47 53]
 [57 61 45 54]]
[[37 62 43 63]
 [57 40 47 53]
 [57 61 45 54]]


In [107]:
"Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices"
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57943051 0.51096648 0.48044149 0.48400775 0.49547179 0.48811204
 0.65376866 0.52476612 0.32042178 0.28600412]


In [106]:
"How to get the diagonal of a dot product"
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([0.62838822, 0.75748348, 1.05078292, 1.13081015, 0.72506167])

In [105]:
"Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value"
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [104]:
"Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)"
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [103]:
"How to swap two rows of an array"
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [102]:
"Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles"
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 0, 43) ( 0, 88) ( 9, 14) ( 9, 98) (12, 78) (12, 79) (14, 98) (15, 40)
 (15, 58) (15, 59) (15, 80) (20, 48) (20, 74) (20, 76) (20, 89) (22, 75)
 (22, 97) (40, 59) (41, 67) (41, 85) (43, 88) (48, 74) (57, 88) (57, 94)
 (58, 80) (67, 85) (75, 97) (76, 89) (78, 79) (88, 94)]


In [101]:
"Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C"
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


In [ ]:
"How to compute averages using a sliding window over an array"

In [100]:
"Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])"
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])

    return np.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

AttributeError: module 'numpy' has no attribute 'stride_tricks'

In [99]:
"How to negate a boolean, or to change the sign of a float inplace?"
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.29074398, -0.621516  ,  0.23094126,  0.41451497,  0.75649107,
       -0.34827369,  0.17470218, -0.02705511, -0.60614833,  0.21167159,
       -0.37708953, -0.33775862,  0.67982769, -0.29106855,  0.72177455,
        0.75129686, -0.61975453, -0.6844148 ,  0.72409824,  0.33689507,
       -0.66462227, -0.6285507 , -0.59404185,  0.3883661 ,  0.43957334,
       -0.391439  ,  0.2160728 ,  0.09574149, -0.43101828,  0.07672431,
        0.55518966,  0.58054157, -0.75158468,  0.56247435, -0.06738208,
       -0.94658138, -0.60128478,  0.67818826, -0.20692859, -0.45572325,
       -0.80643342, -0.10469837, -0.43978165,  0.36568218,  0.51467201,
       -0.53422196,  0.61707911, -0.77738261, -0.26265456, -0.04755179,
       -0.71561391, -0.18353367, -0.20358217,  0.00132195, -0.70703267,
       -0.43717505, -0.50107129,  0.59363718, -0.56054499, -0.99027566,
        0.00858257, -0.05115694,  0.43195779,  0.37118993, -0.89980486,
       -0.81826066,  0.06191269, -0.07155238,  0.59142157, -0.85

In [98]:
"Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?"
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.93300909 1.93695807 0.3656308  2.97604596 1.63401493 9.28780254
 1.17622646 2.58870577 5.07505549 5.36101495]


In [97]:
"Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?"
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([P0,P1,p]))

[[[-0.89820127  4.39526924]
  [-2.82219059  5.55454304]
  [-7.52093774 -4.29443617]
  [ 1.96647177  1.50946455]
  [ 8.27968765 -1.72600704]
  [-6.92282006  9.2003509 ]
  [ 6.74779043 -8.61655497]
  [ 6.34703671  4.00143225]
  [-3.19019735 -4.61668756]
  [ 7.15164263  3.74426924]]

 [[ 9.53786811  8.97221192]
  [ 2.4040631   2.4321736 ]
  [-3.61081247 -6.97433606]
  [ 0.66637836 -5.82727149]
  [-3.71912554  5.42961903]
  [-6.85108127 -8.02964551]
  [ 3.9650367   9.56532344]
  [-9.90418986  1.31780651]
  [-3.67513182 -9.07847415]
  [ 5.05926182 -5.28692652]]

 [[ 3.69638528  3.71970242]
  [-3.76457855  5.24220866]
  [ 3.00042489 -1.43266492]
  [-9.2848285   7.20137078]
  [ 3.73858501  7.39631349]
  [-0.94230952 -1.95005958]
  [-5.15075473  3.1055544 ]
  [ 6.54697279 -1.84965285]
  [-0.95572089 -5.11106661]
  [-1.26005933 -5.57073137]]]


In [90]:
"Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)"
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(r)
print(z)

[slice(1, 5, None), slice(1, 5, None)]
[slice(0, 4, None), slice(0, 4, None)]


In [88]:
"Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?"
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [79]:
"Compute a matrix rank"
rank = np.linalg.matrix_rank(Z)
print(rank)

1


In [78]:
"How to find the most frequent value in an array?"
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [70]:
"Create a 2D array subclass such that Z[i,j] == Z[j,i]"
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  8 11  5  8]
 [ 8  2 11  8  4]
 [11 11  8 42 14]
 [ 5  8 42  5  9]
 [ 8  4 14  9  9]]


In [69]:
"Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) "
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [68]:
"Consider a 16x16 array, how to get the block-sum (block size is 4x4)?"
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [66]:
"How to implement the Game of Life using numpy arrays?"
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    Career = (N==3) & (Z[1:-1,1:-1]==0)
    College = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][Career | College ] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
"How to get the n largest values of an array"
arr = np.array([2,100,90,88,60,99,80])
print(arr[np.argsort(arr)[-4:]])


[ 88  90  99 100]


In [31]:
"Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)"
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian[1, 2, 3], [4, 5], [6, 7])


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [30]:
"How to create a record array from a regular array?"
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [29]:
"Consider a large vector Z, compute Z to the power of 3 using 3 different methods"
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.3 s ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
223 ms ± 9.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
191 ms ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
"Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?"
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 7]


In [ ]:
# prompt: Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


In [59]:
"Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])"
Z = np.random.randint(0,8,(10,3))
print(Z)

[[0 0 4]
 [3 4 1]
 [6 2 6]
 [7 7 3]
 [5 1 6]
 [7 0 5]
 [2 4 0]
 [5 5 7]
 [3 1 2]
 [4 3 0]]


In [23]:
"Convert a vector of ints into a matrix binary representation"
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [22]:
"Given a two dimensional array, how to extract unique rows? "
Z = np.random.randint(0,2,(6,3))
unique_row = np.unique(Z, axis=0)
print(unique_row)

[[0 1 0]
 [1 0 1]
 [1 1 0]]


In [20]:
"Given a two dimensional array, how to extract unique rows? "
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# Get unique rows
unique_rows = np.unique(array, axis=0)

# Print the unique rows
print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# prompt: Given a two dimensional array, how to extract unique rows?

import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# Get unique rows
unique_rows = np.unique(array, axis=0)

# Print the unique rows
print(unique_rows)


In [19]:
"Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function"
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.18393338, 0.44952658, 0.05827014, 0.01474274, 0.44139075,
        0.22093434, 0.22982217, 0.17809461, 0.10614902, 0.26426485],
       [0.20203806, 0.49377378, 0.06400571, 0.01619388, 0.48483713,
        0.24268105, 0.25244372, 0.19562458, 0.11659734, 0.29027661],
       [0.3017828 , 0.73754634, 0.09560487, 0.02418869, 0.72419773,
        0.36249095, 0.37707336, 0.29220303, 0.17416061, 0.43358408],
       [0.37718528, 0.92182728, 0.11949239, 0.03023239, 0.90514343,
        0.45306176, 0.47128769, 0.36521193, 0.21767581, 0.541918  ],
       [0.06613218, 0.16162467, 0.02095069, 0.00530067, 0.15869948,
        0.07943566, 0.08263122, 0.06403288, 0.03816526, 0.09501489],
       [0.22276949, 0.54444064, 0.07057343, 0.01785556, 0.53458698,
        0.26758292, 0.27834734, 0.21569791, 0.12856156, 0.32006232],
       [0.04093837, 0.10005191, 0.01296929, 0.00328132, 0.0982411 ,
        0.04917374, 0.05115192, 0.03963883, 0.02362577, 0.05881788],
       [0.38796337, 0.94816856, 0.1229069

In [18]:
# prompt: Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

import numpy as np

def equidistant_sampling(X, Y, num_points):
  """
  Samples a path described by two vectors (X,Y) using equidistant samples.

  Args:
      X: A numpy array representing the X coordinates of the path.
      Y: A numpy array representing the Y coordinates of the path.
      num_points: The number of equidistant samples to generate.

  Returns:
      A tuple of two numpy arrays representing the X and Y coordinates of the sampled points.
  """

  # Calculate the total length of the path.
  path_length = np.sum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))

  # Generate equally spaced points along the path.
  t = np.linspace(0, path_length, num_points)

  # Interpolate the X and Y coordinates at the equally spaced points.
  X_sampled = np.interp(t, np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2)), X[:-1])
  Y_sampled = np.interp(t, np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2)), Y[:-1])

  return (X_sampled, Y_sampled)


In [12]:
"Considering a path described by two vectors (X,Y), how to sample it using equidistant samples"
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [11]:
"Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n."
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [10]:
"Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). "
X = np.random.random(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.44042476 0.55417697]
