<a href="https://colab.research.google.com/github/Faith-Mueni/Python-Data-Analysis/blob/main/2NumPyDailyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
print (np.__version__)
np.show_config()


1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [5]:
"How to add a border (filled with 0's) around an existing array"
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
"""What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1"""

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [4]:
"Create a 5x5 matrix with values 1,2,3,4 just below the diagonal"
x = np.diag(1+np.arange(4),k=-1)
print(x)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [5]:
"Create a 8x8 matrix and fill it with a checkerboard pattern"
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
"Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element"
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [7]:
"Create a checkerboard 8x8 matrix using the tile function"
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
"Normalize a 5x5 random matrix"
x = np.random.random((5,5))
X = (x - np.mean (x)) / (np.std (x))
print(X)

[[ 0.88055745  1.28225079  0.92914183  0.28069101  1.14735309]
 [ 0.89968497  0.1757398  -1.03705112 -0.09064642 -0.58551956]
 [-0.92876433 -1.64243591  0.96744066 -1.40074798 -0.17608294]
 [-1.58595182  0.92640399 -1.24279057  0.92024448  0.7806991 ]
 [ 0.8095088  -1.33031379  1.22976137 -1.1160152  -0.0931577 ]]


In [18]:
"Create a custom dtype that describes a color as four unsigned bytes (RGBA)"
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [21]:
"Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)"
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [22]:
"Given a 1D array, negate all elements which are between 3 and 8, in place"
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [23]:
"""What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
"""
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [24]:
"""Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z"""
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

NameError: name 'Z' is not defined

In [28]:
"""What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)"""

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))




nan
0
[-9.22337204e+18]


<ipython-input-28-63621d5d594c>:6: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-28-63621d5d594c>:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-28-63621d5d594c>:8: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [29]:
"How to round away from zero a float array"
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))


[ 7. -7. 10. -5.  7.  4. -4.  6.  5. -5.]


In [39]:
"How to find common values between two arrays?"
x1 = np.random.randint(0,20,10)
x2 = np.random.randint(0,10,10)
"print(np.intersect1d(x1,x2))"
print(x1)
print(x2)
print(np.intersect1d(x1,x2))


[ 9 12  5  7  1 15  3  3  8  6]
[0 7 4 8 2 3 2 6 0 6]
[3 6 7 8]
