<a href="https://colab.research.google.com/github/Faith-Mueni/Python-Data-Analysis/blob/main/3NumPyDailyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
print (np.__version__)
np.show_config()


1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [8]:
"How to ignore all numpy warnings (not recommended)"
#defaults = np.seterr(all= "ignore")
x = np.ones(1) / 0
print(x)

[inf]


In [9]:
""" Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)
"""
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [12]:
"How to get the dates of yesterday, today and tomorrow?"
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-02-19
2024-02-20
2024-02-21


In [13]:
"How to get all the dates corresponding to the month of July 2016"
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [19]:
"How to compute ((A+B)*(-A/2)) in place (without copy)?"
A = np.ones(3)*1
B = np.ones(3)*2
w = np.add(A,B,out=B)
x = np.divide(A,2,out=A)
y = np.negative(A,out=A)
z = np.multiply(A,B,out=A)
print (A)
print (B)
print (w)
print (x)
print (y)
print (z)


[-1.5 -1.5 -1.5]
[3. 3. 3.]
[3. 3. 3.]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


In [16]:
x =np.timedelta64(2)
print(x)

2 generic time units


In [4]:
"Extract the integer part of a random array of positive numbers using 4 different methods"
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))



[1. 5. 0. 5. 3. 2. 3. 5. 5. 5.]
[1. 5. 0. 5. 3. 2. 3. 5. 5. 5.]
[1. 5. 0. 5. 3. 2. 3. 5. 5. 5.]
[1 5 0 5 3 2 3 5 5 5]
[1. 5. 0. 5. 3. 2. 3. 5. 5. 5.]


In [3]:
"Create a 5x5 matrix with row values ranging from 0 to 4"
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [5]:
" Consider a generator function that generates 10 integers and use it to build an array"
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [6]:
"Create a vector of size 10 with values ranging from 0 to 1, both excluded"
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [7]:
"Create a random vector of size 10 and sort it"
Z = np.random.random(10)
Z.sort()
print(Z)


[0.02017758 0.07284895 0.1043437  0.23439471 0.29619792 0.46165435
 0.52687881 0.89884929 0.94493677 0.95974996]


In [8]:
"How to sum a small array faster than np.sum"
Z = np.arange(10)
np.add.reduce(Z)

45

In [10]:
"Consider two random array A and B, check if they are equal"
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)


False


In [13]:
"Make an array immutable (read-only)"
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

In [14]:
"Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates"
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.65298768 0.79706024 0.41621257 0.97467503 1.16097989 0.95730842
 0.969839   0.32066727 0.41407752 0.9907917 ]
[0.84393065 1.00423376 0.89852911 0.05467958 0.89886283 0.42876489
 0.87474793 0.43919903 0.50225709 1.53483013]


In [15]:
"Create random vector of size 10 and replace the maximum value by 0"
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.5482222  0.38767678 0.53442741 0.07893326 0.05980095 0.05507836
 0.47809845 0.         0.34922822 0.02763675]
